version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "8082:8080"
    volumes:
      - /Users/kalle/docker-volumes/gerrit/etc:/var/gerrit/etc
      - /Users/kalle/docker-volumes/gerrit/git:/var/gerrit/git
      - /Users/kalle/docker-volumes/gerrit/db:/var/gerrit/db
      - /Users/kalle/docker-volumes/gerrit/index:/var/gerrit/index
      - /Users/kalle/docker-volumes/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://localhost:8082

