version: '2'
services:
  jenkins:
    #image: 'jenkins/jenkins'
    build: .
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - '/Users/kalle/docker-volumes/jenkins_home:/var/jenkins_home'
      - '/Users/kalle/playground:/mnt/playground'

    