services:
  db:
    build: .
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: codescene
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080


volumes:
  db:
